### ISSUE TITLE
Make Perl Shut Up

### ISSUE THREAD

**Issue by christopher-besch** [ToddLinux/ToddLinux#19]
All the files leaving in `.0` in root are bad.

**Comment by ghost** [comment]
Perl manpages are not being written to fake root now
204f126aa2bcdaef204a5ba1f3b309dd1ef07b7e

**Comment by christopher-besch** [comment]
And there is really no way around this?

**Comment by ghost** [comment]
You can try if you want to, I don't really have any better idea right now. Manpages directory is set to `none` by Configure script, the manpages are being written for some reason, and they land in root dir.
